global:
  BASE: "/home/moses/Moses/Research/Current/Institute of Science Tokyo/acoustic-robotics"
  PROJECT: "Multi-Task Acoustic Perception for Occluded Object Detection, Distance Estimation, and Material Classification"